# Generated by Django 5.0.1 on 2024-01-11 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('image', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=4096)),
                ('price_discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_dicount_reverse', to='app.money')),
                ('price_standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_standard_reverse', to='app.money')),
            ],
        ),
    ]
